### ISSUE TITLE
Wasn't able to run on the localhost:5000

### ISSUE THREAD

**Issue by sanjayk0508** [bradtraversy/project-mgmt-graphql#6]
everything was going well but after installing apollo/client and connecting it with react , the localhost turned blank and shows an error in console: 
```
"Uncaught TypeError: Cannot set properties of undefined (setting 'resetStoreCallbacks')
    at ApolloClient (bundle.js:76862:30)
    at renderWithHooks (bundle.js:25434:22)
    at mountIndeterminateComponent (bundle.js:29099:17)
    at beginWork (bundle.js:30567:20)
    at HTMLUnknownElement.callCallback (bundle.js:13230:18)
    at Object.invokeGuardedCallbackDev (bundle.js:13279:20)
    at invokeGuardedCallback (bundle.js:13341:35)
    at beginWork$1 (bundle.js:36354:11)
    at performUnitOfWork (bundle.js:35487:16)
    at workLoopSync (bundle.js:35400:9)
ApolloClient @ bundle.js:76862
renderWithHooks @ bundle.js:25434
mountIndeterminateComponent @ bundle.js:29099
beginWork @ bundle.js:30567
callCallback @ bundle.js:13230
invokeGuardedCallbackDev @ bundle.js:13279
invokeGuardedCallback @ bundle.js:13341
beginWork$1 @ bundle.js:36354
performUnitOfWork @ bundle.js:35487
workLoopSync @ bundle.js:35400
renderRootSync @ bundle.js:35369
performConcurrentWorkOnRoot @ bundle.js:34666
workLoop @ bundle.js:69875
flushWork @ bundle.js:69849
performWorkUntilDeadline @ bundle.js:70133
bundle.js:76862 Uncaught TypeError: Cannot set properties of undefined (setting 'resetStoreCallbacks')
    at ApolloClient (bundle.js:76862:30)
    at renderWithHooks (bundle.js:25434:22)
    at mountIndeterminateComponent (bundle.js:29099:17)
    at beginWork (bundle.js:30567:20)
    at HTMLUnknownElement.callCallback (bundle.js:13230:18)
    at Object.invokeGuardedCallbackDev (bundle.js:13279:20)
    at invokeGuardedCallback (bundle.js:13341:35)
    at beginWork$1 (bundle.js:36354:11)
    at performUnitOfWork (bundle.js:35487:16)
    at workLoopSync (bundle.js:35400:9)
ApolloClient @ bundle.js:76862
renderWithHooks @ bundle.js:25434
mountIndeterminateComponent @ bundle.js:29099
beginWork @ bundle.js:30567
callCallback @ bundle.js:13230
invokeGuardedCallbackDev @ bundle.js:13279
invokeGuardedCallback @ bundle.js:13341
beginWork$1 @ bundle.js:36354
performUnitOfWork @ bundle.js:35487
workLoopSync @ bundle.js:35400
renderRootSync @ bundle.js:35369
recoverFromConcurrentError @ bundle.js:34777
performConcurrentWorkOnRoot @ bundle.js:34678
workLoop @ bundle.js:69875
flushWork @ bundle.js:69849
performWorkUntilDeadline @ bundle.js:70133
bundle.js:27773 The above error occurred in the <ApolloClient> component:

    at ApolloClient (http://localhost:3000/static/js/bundle.js:76862:30)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ bundle.js:27773
update.callback @ bundle.js:27801
callCallback @ bundle.js:23098
commitUpdateQueue @ bundle.js:23121
commitLayoutEffectOnFiber @ bundle.js:32335
commitLayoutMountEffects_complete @ bundle.js:33613
commitLayoutEffects_begin @ bundle.js:33599
commitLayoutEffects @ bundle.js:33537
commitRootImpl @ bundle.js:35744
commitRoot @ bundle.js:35612
finishConcurrentRender @ bundle.js:34819
performConcurrentWorkOnRoot @ bundle.js:34737
workLoop @ bundle.js:69875
flushWork @ bundle.js:69849
performWorkUntilDeadline @ bundle.js:70133
bundle.js:76862 Uncaught TypeError: Cannot set properties of undefined (setting 'resetStoreCallbacks')
    at ApolloClient (bundle.js:76862:30)
    at renderWithHooks (bundle.js:25434:22)
    at mountIndeterminateComponent (bundle.js:29099:17)
    at beginWork (bundle.js:30567:20)
    at beginWork$1 (bundle.js:36329:18)
    at performUnitOfWork (bundle.js:35487:16)
    at workLoopSync (bundle.js:35400:9)
    at renderRootSync (bundle.js:35369:11)
    at recoverFromConcurrentError (bundle.js:34777:24)
    at performConcurrentWorkOnRoot (bundle.js:34678:26)
ApolloClient @ bundle.js:76862
renderWithHooks @ bundle.js:25434
mountIndeterminateComponent @ bundle.js:29099
beginWork @ bundle.js:30567
beginWork$1 @ bundle.js:36329
performUnitOfWork @ bundle.js:35487
workLoopSync @ bundle.js:35400
renderRootSync @ bundle.js:35369
recoverFromConcurrentError @ bundle.js:34777
performConcurrentWorkOnRoot @ bundle.js:34678
workLoop @ bundle.js:69875
flushWork @ bundle.js:69849
performWorkUntilDeadline @ `bundle.js:70133"`
```

pls help me out in this.
Thank you

**Comment by Sky-bits** [comment]
@sanjayk0508   I think you have issue with the node version. 

I was able to run the code successfully

**Comment by rv602** [comment]
@sanjayk0508 i assume you are using a mac, as even for me no sites/servers open on localhost:5000
without running the project, open localhost:5000 and you will probably get something like access denied

To run the project on your device successfully, clone the repo. If you notice in the .env file the port is set to be 5000 (PORT=5000). Just change it to 5001 or some other port number and open localhost:5001 or whatever the PORT number you set it to and it should work.
